apiVersion: v1
kind: Service
metadata:
  name: gitops-argocd-image-updater-demo
spec:
  type: ClusterIP
  selector:
    app: gitops-argocd-image-updater-demo
  ports:
    - port: 80
      targetPort: 5000